### ISSUE TITLE
The getter 'length' was called on null -  lamp setting page

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_App#121]
On the lamp setting page I am getting an error after clicking the plus button :

**Visualization**

![image](https://user-images.githubusercontent.com/34707669/101294595-232a8f00-3821-11eb-9498-a4327ffa3c73.png)

**The error**

```Dart

======== Exception caught by widgets library =======================================================
The following NoSuchMethodError was thrown building FutureBuilder<String>(dirty, state: _FutureBuilderState<String>#99b95):
The getter 'length' was called on null.
Receiver: null
Tried calling: length

The relevant error-causing widget was: 
  FutureBuilder<String> file:///G:/TAMIR/Desktop/cybear_jhini/CBJ_App/lib/features/shared_widgets/add_new_devie_widget.dart:27:7
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new _AddNewDeviceWidgetPopup.<anonymous closure> (package:CyBearJinni/features/shared_widgets/add_new_devie_widget.dart:34:60)
#2      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:753:55)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4792:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:15)
...
====================================================================================================

```

**Comment by guyluz11** [comment]
This happens whenever the user is pressing the plus button while he is not logged in to a WiFi.

Should be an easy fix, we need to show toast that say "Please connect the device to a WiFi and try again.".

**Comment by guyluz11** [comment]
Fixed in dev.
Please check it now.

**Comment by guyluz11** [comment]
The popup was totally changed so I am closing this issue.
