### ISSUE TITLE
Find a way for the app to work on the browser

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_App#212]
The app is using [gRPC](https://pub.dev/packages/grpc) to talk to the Hub.

For on going communication we are **opening sockets** and streaming data both ways, like turn on the light (app to hub) and light got turned on (hub to app).
They are not new requests each time, the connection is being kept open and data is transfer between the devices. 

At first glans gRPC does not support browser
![image](https://user-images.githubusercontent.com/9304740/126306404-6e36c0c2-1826-4d37-a2dc-e032d282473b.png)
but
![image](https://user-images.githubusercontent.com/9304740/126308196-df00e3a0-26ea-4fc0-842d-1bae621f26bd.png)
So my guess is that Sockets are not supported on the browser and only websockets.

```dart
Error: gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: Unsupported operation: Socket constructor, details: null, rawResponse: null)


    at Object.createErrorWithStack (http://localhost:35079/dart_sdk.js:5054:12)
    at Object._rethrow (http://localhost:35079/dart_sdk.js:37670:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:35079/dart_sdk.js:37666:13)
    at Object._microtaskLoop (http://localhost:35079/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:35079/dart_sdk.js:37532:13)
    at http://localhost:35079/dart_sdk.js:33303:9
```

gRPC package have `package:grpc/grpc_web.dart` for web, more research is needed.
Also [this](https://flutter.dev/docs/cookbook/networking/web-sockets)

**Comment by guyluz11** [comment]
Recently they added a new constructor that will handle the differences [grpc_or_grpcweb](https://github.com/grpc/grpc-dart/blob/master/lib/grpc_or_grpcweb.dart)

> /// Note that gRPC and gRPC-web are 2 different protocols and server must be
> /// able to speak both of them for this to work.

**Comment by chena-1** [comment]
I will do it

**Comment by guyluz11** [comment]
Sure

**Comment by guyluz11** [comment]
Last [update of grpc package](https://pub.dev/packages/grpc/changelog) version 3.0.1

> Add GrpcOrGrpcWebClientChannel which uses gRPC on all platforms except web, on which it uses gRPC-web.

Will update the package shortly.

**Comment by guyluz11** [comment]
Hi @chena-1  I am removing you from Assignees but your pr will still be merged if it will be accepted

Thanks
